find_package(OpenCV 4 REQUIRED)
set(INCLUDE_DIRS ${OpenCV_INCLUDE_DIRS})
set(LINK_DIRS)
set(RUNTIME_ENVS)
if (UNIX)
    list(APPEND RUNTIME_ENVS LD_LIBRARY_PATH ${OpenCV_DIR}/lib)
else()
    list(APPEND RUNTIME_ENVS PATH ${OpenCV_DIR}/x64/vc15/bin)
endif()
set(LIBRARIES ${OpenCV_LIBS})
