set(ION_BB_INCLUDE_DIRS)
set(ION_BB_LINK_DIRS)
set(ION_BB_RUNTIME_ENVS)
set(ION_BB_LIBRARIES)

file(GLOB childs ${CMAKE_CURRENT_LIST_DIR}/ion-bb-*)
foreach(child ${childs})
    if(IS_DIRECTORY ${child})
        set(INCLUDE_DIRS)
        set(LINK_DIRS)
        set(RUNTIME_ENVS)
        set(LIBRARIES)
        include(${child}/config.cmake)
        list(APPEND ION_BB_INCLUDE_DIRS ${INCLUDE_DIRS})
        list(APPEND ION_BB_LINK_DIRS    ${LINK_DIRS})
        list(APPEND ION_BB_RUNTIME_ENVS ${RUNTIME_ENVS})
        list(APPEND ION_BB_LIBRARIES    ${LIBRARIES})
    endif()
endforeach()
